### PR TITLE
Add .NET 4.0 Compatibility

### PR DESCRIPTION
**Pull request by petersondrew**
- Add Microsoft.Bcl NuGet package to enable compatibility with .NET 4.0 as
  a PCL
- Remove clickonce signing from GenerateData project to allow others to
  build the solution

### CODE REVIEW

**Comment by petersondrew** [comment]
@dprotaso Have you had a chance to review this by chance?

**Comment by dprotaso** [comment]
Not yet - sorry I'll have time this weekend

**Comment by petersondrew** [comment]
No worries, just wasn't sure if you'd see it or not.
Thanks :smiley:

**Comment by dprotaso** [comment]
I've simplified this pull request - do you mind taking a look at the following and see if there's anything I missed?
https://github.com/dprotaso/Google.PhoneNumbers/pull/3

**Pull request closed without merging**
